### ISSUE TITLE
Consolidate Slides 94-98

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#11]
In order to better fit the format of previous slides, and clearly communicate information, I recommend putting all the bullet points on Slide 94, and then following up with three full slide examples: restaurant grease, MetroCard, and parking tix.  

I'm going ahead and making this change, but am putting the original markdown here, in case you want to go back:

---

# Benefits
+ Time, money, lives saved

---

# Benefits
+ Time, money, lives saved
+ Better delivery of services to stakeholders

---

---

# Benefits
+ Time, money, lives saved
+ Better delivery of services to stakeholders
+ More transparency
+ More accountability

---

---

**Comment by datapolitan** [comment]
@juliaem This is fine. There's a flow I was going for with the slides, but it's fine.
