### ISSUE TITLE
Updated PreK Exercise

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#12]
I updated Slide 99 to reflect how I actually talk about the exercise these days...

Original Text here:

+ Define the analytical problem and data needs in one of these key areas:
Capacity, Outreach, Enrollment (CBOs/Students), Monitoring/Evaluation
+ Situation: ~104,000 4-year olds in NYC, 58,528 current seats, 26,364 in public schools, 32,164 in community based organizations
+ Goals: .red[Increase enrollment by 30,000 for 2014-2015], .red[Increase enrollment by 20,000 for 2015-2016]

**Comment by datapolitan** [comment]
Sounds great.
