### ISSUE TITLE
Replace datadriven_alert.png

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#13]

**Comment by datapolitan** [comment]
Slide numbers change so it's best to have a better reference. Right now, this the Alerts slide (with image `datadriven_alert.png`)

**Comment by datapolitan** [comment]
Please let me know which slide this pertains to

**Comment by juliaem** [comment]
Sorry!  I've been sleeping notifications from Github and missed your comment... Funny, cuz we're talking the dangers of missing alerts :) 

The image on the reports slide is cut off. I'm not sure if it's the image or if it needs some extra padding or margin. I can take a look next week.

**Comment by datapolitan** [comment]
No worries. I'll tag you with this to replace at your leisure.
