### ISSUE TITLE
Compliance audit of images

### ISSUE THREAD

**Issue by datapolitan** [datapolitan/data-driven-gov#2]
Please identify the images that need to be replaced and either identify them in this Issue [using a checklist](https://github.com/blog/1825-task-lists-in-all-markdown-documents) or create an open issue for each one. I'd like to have some visibility on this so I can help you select images in the easiest way possible.

**Comment by juliaem** [comment]
Sorry-- I didn't see your instructions on this until now... But I added images to all the slides that are creative commons licensed and properly attributed. 

All images that came from gov't sources are already in the public domain, so I didn't have to replace everything. 

Let me know if you still want a checklist?
