### ISSUE TITLE
Mention new noise sensor project

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#35]
In the value of data, mention new initiative to measure noise w/ sensors in NYC

**Comment by juliaem** [comment]
See Mark's email for link to NYTimes article

**Comment by datapolitan** [comment]
Here's the link: http://www.nytimes.com/2016/11/07/nyregion/to-create-a-quieter-city-theyre-recording-the-sounds-of-new-york.html

Can we use the NY Times images? How do we want to use this?

**Comment by juliaem** [comment]
No we can't use NYTimes images... Also not sure we need a new slide. Just a great example of direct measure, compared to the 311 noise complaints.
