### ISSUE TITLE
Add Lean Six Sigma to performance analytics?

### ISSUE THREAD

**Issue by datapolitan** [datapolitan/data-driven-gov#43]
Review whether we pitch this as an example of how this is done.

http://asq.org/learn-about-quality/six-sigma/overview/overview.html

**Comment by juliaem** [comment]
Six sigma feels very proprietary to me and a little jargon-y, but I don't actually know how to apply six sigma principles to my work. Is there something about the method that people could walk away with and improve how they set and measure performance metrics? 

Also is there a more open source model that people could apply to their work?

**Comment by datapolitan** [comment]
Doesn't seem relevant unless it comes up in conversation.
