### ISSUE TITLE
Update UPK to more current example? 

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#44]
- homelessness?
- IDNYC? 
- Riker's?

**Comment by datapolitan** [comment]
It would be nice to have something relatively non-controversial and easy to replicate in other municipalities.

**Comment by juliaem** [comment]
What about the census? 

There's a group of people that come up with questions for the long form and ACS. What do you want to know about the American people that can inform the work that you do in your agency?  Consider questions of identity, economic class, family, job, housing, etc?  

In discussion we can talk about the changing questions over the years and how it reflects the data we collect and the kinds of analysis we do. 

It's all cultural :)

**Comment by juliaem** [comment]
Maybe use a Jeopardy graphic to encourage the importance of questions
