### ISSUE TITLE
Slides 23-24: What is Analysis & Data Driven Culture

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#8]
I have a handwritten note that you wanted to move the "What is Analysis slide" to later in the deck.  But I also replace the gnomes slide (which isn't going to work across a broader audience as well as it does in the classroom) with a transition about how Analytics Matter. Let's chat?

**Comment by juliaem** [comment]
Also I added the compass image to slide 24 as noted, and the flow is pretty off... Let's look thru the previous and following slides and figure out what works.

**Comment by datapolitan** [comment]
It seemed to fit where it was, but let's keep watching this
