### ISSUE TITLE
How to center captions

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#9]
We need to add a style for captions so that they appear tiny, centered, and below each image. 
Also what's the markdown tag for a specific class like that?

**Comment by datapolitan** [comment]
We have several options
- [ ] You can embed custom HTML `<p class="caption">Caption Text Here</p>`. See the `<p class="footer">` example in `index.html`
- [ ] Use `.caption[test text]`. This creates a `<span class="caption"></span>` that's virtually the same

Let me know which would be useful for you. In the meantime, if you leave off any `#`, it will default to a `<p>` tag, which should be fine for now.

**Comment by juliaem** [comment]
.caption works for me.

I added this to the stylesheet, but I'm not sure it's working... 

.caption {
   text-align: center; 
}

**Comment by datapolitan** [comment]
It needed to have a `display:block` added to take hold. I also played with the styling to offset the text.
