### ISSUE TITLE
Nolalytics

### ISSUE THREAD

**Issue by juliaem** [datapolitan/data-driven-gov#94]
Consider making this more interactive per Liz's suggestion.  Cut the examples and turn each slide into an opportunity for Q&A.  For example, "If you're scoping a Vision Zero exercise, what question could you ask that would match this type of analysis?"

**Comment by datapolitan** [comment]
@lizdumont @juliaem That's exactly the plan. See [presenters note on the introductory slide](http://www.datapolitan.com/data-driven-gov/#p63). The examples are there for backup in case they aren't able to come up with an example. My intention is for these examples to be discussed quickly with only as much context as necessary to demonstrate the key ideas.
